adminset/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^dbmanage/',include('dbmanage.urls')),
    url(r'^test/$',views.test,name='test'),
    url(r'^add/$',views.add,name='add'),
    url(r'^ajax_dict',views.ajax_dict,name='ajax_dict'),
    url(r'^ajax_list',views.ajax_list,name='ajax_list'),
    url(r'^forbidden/',views.forbidden,name='forbidden'),

]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group


urlpatterns = [
    url(r'asset/$', asset.asset, name='cmdb'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_del, name='asset_del'),
    url(r'^asset/edit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^group/del/$', group.group_del, name='group_del'),
    url(r'^group/add/$', group.group_add, name='group_add'),
    url(r'^group/edit/(?P<ids>\d+)/$', group.group_edit, name='group_edit'),
    url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_del, name='idc_del'),
    url(r'^idc/save/$', idc.idc_save, name='idc_save'),
    url(r'^idc/edit/(?P<ids>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^get/host/', api.get_host, name='get_host'),
    url(r'^get/group/', api.get_group, name='get_group'),
]

dbmanage/archer/archer/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('dbmanage.archer.sql.urls')),
]

if __name__ == '__main__':
    print(urlpatterns)

dbmanage/mypro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.views.static import serve
from myapp import views as myapp_view
urlpatterns = [
    url(r'^$', myapp_view.index, name='index'),
    url(r'^accounts/login/$',myapp_view.login,name='login'),
    url(r'^accounts/logout/$',myapp_view.logout,name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^log_query/$', myapp_view.log_query,name='log_query'),
    url(r'^mysql_query/$', myapp_view.mysql_query,name='mysql_query'),
    url(r'^mysql_admin/$', myapp_view.mysql_admin, name='mysql_admin'),
    url(r'^binlog_parse/$', myapp_view.mysql_binlog_parse,name='binlog_parse'),
    url(r'^tb_check/$', myapp_view.tb_check, name='tb_check'),
    url(r'^dupkey_check/$', myapp_view.dupkey_check, name='dupkey_check'),
    url(r'^meta_data/$', myapp_view.meta_data,name='meta_data'),
    url(r'^mysql_exec/$', myapp_view.mysql_exec,name='mysql_exec'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^sqlcheck/$', myapp_view.inception,name='inception'),

    url(r'^task/$', myapp_view.task_manager,name='task_manager'),
    url(r'^pre_query/$', myapp_view.pre_query,name='pre_query'),
    url(r'^pass_reset/$', myapp_view.pass_reset,name='pass_reset'),
    url(r'^pre_set/$', myapp_view.pre_set,name='pre_set'),
    url(r'^set_dbgroup/$', myapp_view.set_dbgroup,name='set_dbgroup'),
    url(r'^set_ugroup/$', myapp_view.set_ugroup,name='set_ugroup'),
    url(r'^fast_dbset/$', myapp_view.fast_dbset,name='fast_dbset'),
    url(r'^set_dbname/$', myapp_view.set_dbname,name='set_dbname'),
    url(r'^update_task/$', myapp_view.update_task,name='update_task'),
    url(r'^get_rollback/$', myapp_view.get_rollback,name='get_rollback'),
    url(r'^get_single_rollback/$', myapp_view.get_single_rollback,name='get_single_rollback'),
    url(r'^get_tblist/$', myapp_view.get_tblist, name='get_tblist'),
    url(r'^diff/$', myapp_view.diff,name='diff'),
    url(r'^salt/', include('salt.urls')),
    url(r'^mongodb/', include('dbmanage.mongodb.urls')),
    url(r'^chartapi/', include('dbmanage.chartapi.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^passforget/', include('dbmanage.passforget.urls')),
    url(r'^blacklist/', include('dbmanage.blacklist.urls')),
    url(r'^site_media/(?P<path>.*)$',serve,{'document_root': settings.MEDIA_ROOT}),

]

dbmanage/myapp/models.py
from __future__ import unicode_literals
# from django.contrib.auth.models import User
from django.db import models
import pytz
from django.conf import settings
from datetime import datetime
from django.utils import timezone
tz = pytz.timezone('UTC')
s_time = tz.localize(datetime.strptime('2199-01-01 00:00:00','%Y-%m-%d %H:%M:%S'))
read_write = (
    ('read', 'read'),
    ('write', 'write'),
    ('all','all'),
    ('idle','idle'),
)
read_write_account = (
    ('read', 'read'),
    ('write', 'write'),
    ('read_write','read_write'),
    ('admin','admin'),
    ('all','all'),
)
db_type = (
    ('mysql', 'mysql'),
    ('mongodb', 'write'),
)


class Db_instance(models.Model):
    ip = models.CharField(max_length=30)
    port = models.CharField(max_length=10)
    db_type = models.CharField(max_length=30,default='mysql')
    comments = models.CharField(max_length=100,null=True)
    status = models.CharField(max_length=20,choices=(('Idle','Idle'),('InUse','InUse')))

    admin_user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    create_user = models.CharField(max_length=50,null=True)
    create_date =models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s %s' % (self.ip, self.port,self.db_type)
    class Meta:
        unique_together = ("ip","port")



class Db_account(models.Model):

    user = models.CharField(max_length=30)
    passwd = models.CharField(max_length=255)
    instance = models.ForeignKey(Db_instance)
    db_account_role =  models.CharField(max_length=30,choices=read_write_account,default='all')
    tags = models.CharField(max_length=80,db_index=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    # dbname = models.ManyToManyField(Db_name)
    # account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return  u'%s %s' % ( self.tags,self.db_account_role)

    class Meta:
        unique_together = ('instance','db_account_role')

class Db_name (models.Model):
    dbtag = models.CharField(max_length=80)
    dbname = models.CharField(max_length=30)
    dbaccount = models.ForeignKey(Db_account)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s' % (self.dbtag, self.dbname)

class Instance_account_admin(models.Model):
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    db_account = models.ForeignKey(Db_account)
class Db_database_permission(models.Model):
    db_name = models.ForeignKey(Db_name)
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    permission = models.CharField(max_length=20,choices=read_write_account,default='read')
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_database_permission_detail(models.Model):
    permission = models.ForeignKey(Db_database_permission)
    permission_detail = models.CharField(max_length=500,null=True)
    black_table = models.CharField(max_length=500,null=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_group(models.Model):
    groupname = models.CharField(max_length=30,unique=True)
    dbname = models.ManyToManyField(Db_name)
    account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return self.groupname

class Oper_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    dbtag = models.CharField(max_length=35)
    dbname = models.CharField(max_length=300)
    sqltext = models.TextField()
    sqltype = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)
    login_time = models.DateTimeField()
    group_id = models.IntegerField()
    host_id = models.IntegerField()
    def __unicode__(self):
        return self.dbtag
    class Meta:
        index_together = [["dbtag","sqltype", "create_time"],]

class Login_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    action = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)

# class Task_scheduler(models.Model):
#     task = models.OneToOneField(Task)
#     appoint_time = models.DateTimeField(db_index=True)
#     def __unicode__(self):
#         return  self.task.id


class User_profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    select_limit = models.IntegerField(default=200)
    export_limit = models.IntegerField(default=200)
    task_email = models.IntegerField(db_index=True)
    def __unicode__(self):
        return  self.user.username
    class Meta:
        permissions = (('can_mysql_query','can see mysql_query view'),
                      ('can_log_query','can see log_query view'),
                      ('can_see_execview','can see mysql exec view'),
                      ('can_see_inception', 'can see inception view'),
                      ('can_see_metadata', 'can see meta_data view'),
                      ('can_see_mysqladmin', 'can see mysql_admin view'),
                      ('can_export','can export csv'),
                      ('can_insert_mysql','can insert mysql'),
                      ('can_update_mysql','can update mysql'),
                      ('can_delete_mysql','can delete mysql'),
                      ('can_create_mysql','can create mysql'),
                      ('can_drop_mysql','can drop mysql'),
                      ('can_truncate_mysql','can truncate mysql'),
                      ('can_alter_mysql','can alter mysql'),
                      ('can_query_mongo', 'can query mongo'),
                      ('can_see_taskview', 'can see task view'),
                      ('can_admin_task','can admin task'),
                      ('can_delete_task', 'can delete task'),
                      ('can_update_task', 'can update task'),
                      ('can_query_pri', 'can query pri'),
                      ('can_set_pri', 'can set pri'),
                      ('can_oper_saltapi', 'can oper saltapi'),
                       )

class Upload(models.Model):
    username = models.CharField(max_length = 40)
    filename = models.FileField(upload_to = 'upload_sql')
    def __unicode__(self):
        return self.username
# Create your models here.
class Task(models.Model):
    user = models.CharField(max_length=35)
    instance = models.CharField(max_length=100)
    db_account_role = models.CharField(max_length=15)
    dbtag = models.CharField(max_length=35)
    sqltext = models.TextField()
    create_time = models.DateTimeField(db_index=True)
    update_time = models.DateTimeField()
    status = models.CharField(max_length=20,db_index=True)
    sqlsha =  models.TextField()
    sche_time = models.DateTimeField(db_index=True,null=True)
    specification = models.CharField(max_length=100,default='')
    operator = models.CharField(max_length=35, default='')
    backup_status = models.SmallIntegerField(default=1)
    def __unicode__(self):
        return self.dbtag
#backup_status
# o donot  backup
# 1 need  backup
# 2

class Incep_error_log(models.Model):
    task_id = models.IntegerField(null=True,default=0)
    myid = models.IntegerField()
    stage = models.CharField(max_length= 20)
    errlevel = models.IntegerField()
    stagestatus = models.CharField(max_length=40)
    errormessage = models.TextField()
    sqltext = models.TextField()
    affectrow = models.IntegerField()
    sequence = models.CharField(max_length=30,db_index=True)
    backup_db = models.CharField(max_length=100)
    execute_time = models.CharField(max_length=20)
    sqlsha = models.CharField(max_length=50)
    create_time = models.DateTimeField(db_index=True)
    finish_time = models.DateTimeField()

class MySQL_monitor(models.Model):
    tag = models.CharField(max_length=20)
    monitor = models.SmallIntegerField(default=1)
    instance = models.OneToOneField(Db_instance)
    # instance = models.ForeignKey(Db_instance)
    check_longsql = models.SmallIntegerField(default=0)
    longsql_time = models.SmallIntegerField(default=1200)
    longsql_autokill = models.SmallIntegerField(default=0)
    check_active = models.SmallIntegerField(default=0)
    active_threshold = models.SmallIntegerField(default=30)
    # account = models.OneToOneField(Db_account)
    table_check = models.SmallIntegerField(default=0)
    account = models.ForeignKey(Db_account)
    check_connections = models.SmallIntegerField(default=0)
    connection_threshold = models.IntegerField(default=1000)
    check_delay = models.SmallIntegerField(default=0)
    delay_threshold = models.IntegerField(default=3600)
    check_slave = models.SmallIntegerField(default=0)
    replchannel = models.CharField(max_length=30,default='0')
    alarm_times = models.SmallIntegerField(default=3)
    alarm_interval = models.SmallIntegerField(default=60)
    mail_to = models.CharField(max_length=255)
    def __unicode__(self):
        return self.tag
    class Meta:
        db_table = 'mysql_monitor'

dbmanage/myapp/templates/previliges/fast_dbset.html
{% extends "include/base.html" %}
{% load static %}
{% block title %}
    <title>快速创建DB</title>
{% endblock %}
{% block name %}
    快速创建DB


    <br>
    {% if result %}<span style="color: red"> {{ result }}</span> {% endif %}
{% endblock %}
{%block db_content%}
    {% if info %}
        <br>
        <br>
        <strong> <span style="color:red">{{ info }}</span></strong>
    {% endif %}


<div class="col-md-9 text-left">
<form role="form" method='post'>

 {% csrf_token %}
<input name="authenticity_token" type="hidden" value="{{ token }}">
     <div class="box box-info">
         <div class="box-header with-border">
              <h3 class="box-title">Instance</h3>
         </div>
     <div class="box-body">
         <div class="form-group col-sm-3">
               <strong>CHOOSE HOST GROUP</strong> </br>
                    <select id="id_select_group" onchange="change_group(-1,{{ select_group|default:0 }},'{{ select_host.ip|default:0 }}')" class="form-control col-md-5" style="width: 200px ;" name = "select_group">
                        <option value ="" selected disabled >---Select Host Group---</option>
                        {% for group in host_group %}
                            {% if group.id == select_group %}
                                <option selected="selected" value ="{{ group.id }}">{{ group.name }}</option>
                            {% else %}
                                <option value ="{{ group.id }}">{{ group.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
           </div>
            <div class="form-group col-sm-9">
                <strong>&nbsp;&nbsp;CHOOSE HOST</strong> <br>
                <select id="select_host" onchange='changeHost(this.value)' style="width: auto" class="form-control col-md-5" name = "select_host">
                    <option  value ="" selected disabled >--Select Host---</option>
{#                    {% for key,value in host_list.items %}#}
{#                        {% if key == select_host %}#}
{#                                <option selected="selected" value ="{{ key }}">{{ key }}#}
{#                                    {% if value|length == 0 %}#}
{#                                        无账号#}
{#                                    {% else %}#}
{#                                       已有账号列表: {{ value }}#}
{#                                    {% endif %}#}
{#                                </option>#}
{#                        {% else %}#}
{#                            <option  value ="{{ key }}">{{ key }}#}
{#                                {% if value|length == 0 %}#}
{#                                    无账号#}
{#                                   {% else %}#}
{#                                   已有账号列表: {{ value }}#}
{#                                   {% endif %}#}
{#                            </option>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}

                </select>

           </div>
             {% if message %}

                  <h1><strong style="color: red">{{ message }}</strong> </h1>

                {% endif %}

            <div class="form-group  col-sm-6  ">
                <br>
                &nbsp;{{ form.comment }}
                    <br>
                {{ form.port }} <span style="color: red">{{ form.errors.port.0 }}</span>
                <br>
                <select id='db_type' class="form-control col-md-3"  name="db_type">
                <option selected disabled value="no">--DB TYPE--</option>
                    {% if db_type is not None %}
                        {% if db_type == 'mysql' %}
                            <option value="mysql" selected="selected">MySQL</option>
                            <option value="mongodb"  >Mongodb</option>
                        {% else %}
                            <option value="mongodb"  selected="selected">Mongodb</option>
                            <option value="mysql" >MySQL</option>
                        {% endif %}
                    {% else %}
                        <option value="mysql" >MySQL</option>
                        <option value="mongodb"  >Mongodb</option>
                {% endif %}
                </select>
{#                {% if db_type is None %}<span style="color:red">Must be choice db type</span>{% endif %}#}

             </div>
     </div>
     </div>

    <div class="box box-info">
        <div class="box-header with-border">
              <h3 class="box-title">DB_ACCOUNT FOR NORMAL USER(EXP:query,exec)</h3>
        </div>
        <div class="box-body">
            <div class="form-group">
                  <label for="normal_db_account" class="col-sm-3 control-label text-left">Normal Account:</label>

                  <div class="col-sm-9">
                      {{ form.normal_db_account }}<span style="color: red">{{ form.errors.normal_db_account}}</span>

                  </div>
                </div>

                <div class="form-group">
                  <label for="normal_db_password" class="col-sm-3 control-label">Normal Password:</label>
                  <div class="col-sm-9">
                                {{ form.normal_db_password }}<span style="color: red">{{ form.errors.normal_db_password }}</span>
{#                                     <span style="color: red">#}
{#                                       {% if form|all_errors %}#}
{#                                             {{ form|all_errors }}#}
{#                                        {% endif %}#}
{#                                    </span>#}

                 </div>
                </div>

                <div class="form-group">
                      <label for="normal_db_password_again" class="col-sm-3 control-label">Normal Password:</label>
                      <div class="col-sm-9">
                          {{ form.normal_db_password_again }}<span style="color: red">{{ form.errors.normal_db_password_again }}</span>
                     </div>
                </div>

        </div>

 <div class="box box-info">
        <div class="box-header with-border">
              <h3 class="box-title">DB_ACCOUNT FOR ADMIN USER(EXP:reload,process,super,replication client...)</h3>
        </div>
        <div class="box-body">

             <div class="form-group">
                 <label for="admin_db_account" class="col-sm-3 control-label">Admin Account</label>
                 <div class="col-sm-9">
                        {{ form.admin_db_account }}<span style="color: red">{{ form.admin_db_account.errors }}</span>
                 </div>
             </div>

            <div class="form-group">
                <label for="admin_db_password" class="col-sm-3 control-label">Admin Password</label>
                <div class="col-sm-9">
                    {{ form.admin_db_password }}<span style="color: red">{{ form.admin_db_password.errors }}</span>
                </div>
            </div>

             <div class="form-group">
                <label for="admin_db_password_again" class="col-sm-3 control-label">Admin Password:</label>
                <div class="col-sm-9">
                    {{ form.admin_db_password_again }}<span style="color: red">{{ form.admin_db_password_again.errors }}</span>
                </div>
            </div>

             <div class="box-footer">
                   {% if  form.non_field_errors %}
                        <br>
                            <h1><span style="color: red">{{ form.non_field_errors }}</span></h1>
                       <br>

                    {% endif %}
                <button type="submit" name='create' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-info" >创建</button>
                 <button type="button" name='back' onclick='javascrtpt:window.location.href="{% url 'dbmanage'  %}"'  class="btn btn-info" >返回</button>

              </div>
            </div>
 </div>
    </div>
</form>


        <!-- /.modal -->
</div>
<script>

    function changeHost(str) {
{#        var host = $('#select_host').find("option:selected").val();#}
{#        console.log(str)#}

        $.ajax({ url: "/dbmanage/get_hostdetail/", data: {'selected_host':str}, dataType: 'json',type: 'GET',success: function(ret){

            $("#db_type").find("option:selected").attr("selected",false);
            if(ret.result === 1){


                $("#id_comment").val(ret.comments);
                $("#id_port").val(ret.port);
                $("#db_type").find("option[value='"+ret.db_type+"']").attr("selected",true);
{#                $("#db_type").find("option:selected").val(ret.db_type);#}

            }
            else{
                $("#id_comment").val('');
                $("#id_port").val('');
                 $("#db_type").find("option[value='no']").attr("selected",true);
{#                $("#db_type").find("option:selected").val('no');#}

            }


      }});


    }



    </script>




<script src="{% static 'myapp/select_group.js' %}"></script>

<script>
    var h = '';
    if (({{  select_host.id|default:0 }}) > 0 && ({{ select_host.group_id|default:0 }}) == 0){
        h = '{{ select_host.id }}';
    }
    else if (({{ select_host.group_id|default:0 }}) >0){
        h = '{{ select_host.ip }}';
    }
    else {
        h = 0
    }

    change_group(-2,{{ select_group|default:0 }},h);

</script>

{% endblock %}

dbmanage/myapp/templates/previliges/pass_reset.html
{% extends "include/base.html" %}
{% block title %}
    <title>密码重置</title>
{% endblock %}
{% block name %}
    欢迎使用密码重置功能
{% endblock %}
{%block content%}
    <hr />
    <span id="errorpwd" style="color: #eea236" >{{ info }}</span>

    <form role="form" method='post'>
        {% csrf_token %}


        <div class="col-md-2 main ">
            <input id="id_passwd" type="password" class="form-control" maxlength="25" placeholder="type new password here" name="passwd" onkeydown="clearstage()">

            <input id="id_repasswd" type="password" class="form-control" maxlength="25" placeholder="retype password here" name="repasswd" onkeydown="clearstage()" >

            <button id="id_button" type="submit" name='set' onclick="return checkPass();"  class="btn btn-danger" >重置</button>
        </div>
    </form>
{#    <div class="col-md-11">#}
{#        <div id="map" style="width:1000px;height:500px"></div>#}
{#    </div>#}
{#    <script  src="http://api.map.baidu.com/api?v=2.0&ak=zhskfLsPCGPrPQvGb2WsL2mGZsfGO9XT&callback=initialize"></script>#}
{#    <script type="text/javascript">#}
{#        function getLocation(){#}
{#            var options={#}
{#                enableHighAccuracy:true,#}
{#                maximumAge:1000#}
{#            }#}
{#            if(navigator.geolocation){#}
{#                //浏览器支持geolocation#}
{#                navigator.geolocation.getCurrentPosition(onSuccess,onError,options);#}
{##}
{#            }else{#}
{#                //浏览器不支持geolocation#}
{#                alert("not support");#}
{#            }#}
{#        }#}
{##}
{#        function onSuccess(position) {#}
{#            var longitude =position.coords.longitude;#}
{#            var latitude = position.coords.latitude;#}
{#            var mp = new BMap.Map('map');#}
{#            mp.centerAndZoom(new BMap.Point(longitude, latitude), 14);#}
{#            mp.enableScrollWheelZoom();#}
{#            mp.addControl(new BMap.NavigationControl());#}
{#            mp.addControl(new BMap.ScaleControl());#}
{#            mp.addControl(new BMap.OverviewMapControl());#}
{#            mp.addControl(new BMap.MapTypeControl());#}
{#        }#}
{#        function onError(error){#}
{#            switch(error.code){#}
{#                case 1:#}
{#                    alert("位置服务被拒绝");#}
{#                    break;#}
{##}
{#                case 2:#}
{#                    alert("暂时获取不到位置信息");#}
{#                    break;#}
{##}
{#                case 3:#}
{#                    alert("获取信息超时");#}
{#                    break;#}
{##}
{#                case 4:#}
{#                    alert("未知错误");#}
{#                    break;#}
{#            }#}
{##}
{#        }#}
{#        window.onload = getLocation;#}
{#    </script>#}


    <script>
        function clearstage () {
            document.getElementById("errorpwd").innerText = "";

        }
        function checkPass() {
            var pwd1 = document.getElementById("id_passwd").value;
            var pwd2 = document.getElementById("id_repasswd").value;
            if (pwd1.length < 8){
                document.getElementById("errorpwd").innerText = "密码长度至少8位";
                return false;
            }
            if (pwd1 != pwd2) {
                document.getElementById("errorpwd").innerText = "两次密码输入不一致";
                return false;
            }
            return true;
        }
        {#        function checksame() {#}
        {#            var pwd1 = document.getElementById("id_passwd").value;#}
        {#            var pwd2 = document.getElementById("id_repasswd").value;#}
        {##}
        {#            if (pwd1 != pwd2 && pwd1.length != 0) {#}
        {#                document.getElementById("errorpwd").innerText = "两次输入密码不一致";#}
        {#            }#}
        {#            else#}
        {#            {#}
        {#                document.getElementById("errorpwd").innerText = "";#}
        {#            }#}
        {#        }#}


    </script>
{% endblock %}