adminset/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^dbmanage/',include('dbmanage.urls')),
    url(r'^test/$',views.test,name='test'),
    url(r'^add/$',views.add,name='add'),
    url(r'^ajax_dict',views.ajax_dict,name='ajax_dict'),
    url(r'^ajax_list',views.ajax_list,name='ajax_list'),
    url(r'^forbidden/',views.forbidden,name='forbidden'),

]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group


urlpatterns = [
    url(r'asset/$', asset.asset, name='cmdb'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_del, name='asset_del'),
    url(r'^asset/edit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^group/del/$', group.group_del, name='group_del'),
    url(r'^group/add/$', group.group_add, name='group_add'),
    url(r'^group/edit/(?P<ids>\d+)/$', group.group_edit, name='group_edit'),
    url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_del, name='idc_del'),
    url(r'^idc/save/$', idc.idc_save, name='idc_save'),
    url(r'^idc/edit/(?P<ids>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^get/host/', api.get_host, name='get_host'),
    url(r'^get/group/', api.get_group, name='get_group'),
]

dbmanage/archer/archer/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('dbmanage.archer.sql.urls')),
]

if __name__ == '__main__':
    print(urlpatterns)

dbmanage/mypro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.views.static import serve
from myapp import views as myapp_view
urlpatterns = [
    url(r'^$', myapp_view.index, name='index'),
    url(r'^accounts/login/$',myapp_view.login,name='login'),
    url(r'^accounts/logout/$',myapp_view.logout,name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^log_query/$', myapp_view.log_query,name='log_query'),
    url(r'^mysql_query/$', myapp_view.mysql_query,name='mysql_query'),
    url(r'^mysql_admin/$', myapp_view.mysql_admin, name='mysql_admin'),
    url(r'^binlog_parse/$', myapp_view.mysql_binlog_parse,name='binlog_parse'),
    url(r'^tb_check/$', myapp_view.tb_check, name='tb_check'),
    url(r'^dupkey_check/$', myapp_view.dupkey_check, name='dupkey_check'),
    url(r'^meta_data/$', myapp_view.meta_data,name='meta_data'),
    url(r'^mysql_exec/$', myapp_view.mysql_exec,name='mysql_exec'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^sqlcheck/$', myapp_view.inception,name='inception'),

    url(r'^task/$', myapp_view.task_manager,name='task_manager'),
    url(r'^pre_query/$', myapp_view.pre_query,name='pre_query'),
    url(r'^pass_reset/$', myapp_view.pass_reset,name='pass_reset'),
    url(r'^pre_set/$', myapp_view.pre_set,name='pre_set'),
    url(r'^set_dbgroup/$', myapp_view.set_dbgroup,name='set_dbgroup'),
    url(r'^set_ugroup/$', myapp_view.set_ugroup,name='set_ugroup'),
    url(r'^fast_dbset/$', myapp_view.fast_dbset,name='fast_dbset'),
    url(r'^set_dbname/$', myapp_view.set_dbname,name='set_dbname'),
    url(r'^update_task/$', myapp_view.update_task,name='update_task'),
    url(r'^get_rollback/$', myapp_view.get_rollback,name='get_rollback'),
    url(r'^get_single_rollback/$', myapp_view.get_single_rollback,name='get_single_rollback'),
    url(r'^get_tblist/$', myapp_view.get_tblist, name='get_tblist'),
    url(r'^diff/$', myapp_view.diff,name='diff'),
    url(r'^salt/', include('salt.urls')),
    url(r'^mongodb/', include('dbmanage.mongodb.urls')),
    url(r'^chartapi/', include('dbmanage.chartapi.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^passforget/', include('dbmanage.passforget.urls')),
    url(r'^blacklist/', include('dbmanage.blacklist.urls')),
    url(r'^site_media/(?P<path>.*)$',serve,{'document_root': settings.MEDIA_ROOT}),

]

dbmanage/myapp/models.py
from __future__ import unicode_literals
# from django.contrib.auth.models import User
from django.db import models
import pytz
from django.conf import settings
from datetime import datetime
from django.utils import timezone
tz = pytz.timezone('UTC')
s_time = tz.localize(datetime.strptime('2199-01-01 00:00:00','%Y-%m-%d %H:%M:%S'))
read_write = (
    ('read', 'read'),
    ('write', 'write'),
    ('all','all'),
    ('idle','idle'),
)
read_write_account = (
    ('read', 'read'),
    ('write', 'write'),
    ('read_write','read_write'),
    ('admin','admin'),
    ('all','all'),
)
db_type = (
    ('mysql', 'mysql'),
    ('mongodb', 'write'),
)


class Db_instance(models.Model):
    ip = models.CharField(max_length=30)
    port = models.CharField(max_length=10)
    db_type = models.CharField(max_length=30,default='mysql')
    comments = models.CharField(max_length=100,null=True)
    status = models.CharField(max_length=20,choices=(('Idle','Idle'),('InUse','InUse')))

    admin_user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    create_user = models.CharField(max_length=50,null=True)
    create_date =models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s %s' % (self.ip, self.port,self.db_type)
    class Meta:
        unique_together = ("ip","port")



class Db_account(models.Model):

    user = models.CharField(max_length=30)
    passwd = models.CharField(max_length=255)
    instance = models.ForeignKey(Db_instance)
    db_account_role =  models.CharField(max_length=30,choices=read_write_account,default='all')
    tags = models.CharField(max_length=80,db_index=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    # dbname = models.ManyToManyField(Db_name)
    # account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return  u'%s %s' % ( self.tags,self.db_account_role)

    class Meta:
        unique_together = ('instance','db_account_role')

class Db_name (models.Model):
    dbtag = models.CharField(max_length=80)
    dbname = models.CharField(max_length=30)
    dbaccount = models.ForeignKey(Db_account)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s' % (self.dbtag, self.dbname)

class Instance_account_admin(models.Model):
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    db_account = models.ForeignKey(Db_account)
class Db_database_permission(models.Model):
    db_name = models.ForeignKey(Db_name)
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    permission = models.CharField(max_length=20,choices=read_write_account,default='read')
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_database_permission_detail(models.Model):
    permission = models.ForeignKey(Db_database_permission)
    permission_detail = models.CharField(max_length=500,null=True)
    black_table = models.CharField(max_length=500,null=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_group(models.Model):
    groupname = models.CharField(max_length=30,unique=True)
    dbname = models.ManyToManyField(Db_name)
    account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return self.groupname

class Oper_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    dbtag = models.CharField(max_length=35)
    dbname = models.CharField(max_length=300)
    sqltext = models.TextField()
    sqltype = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)
    login_time = models.DateTimeField()
    group_id = models.IntegerField()
    host_id = models.IntegerField()
    def __unicode__(self):
        return self.dbtag
    class Meta:
        index_together = [["dbtag","sqltype", "create_time"],]

class Login_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    action = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)

# class Task_scheduler(models.Model):
#     task = models.OneToOneField(Task)
#     appoint_time = models.DateTimeField(db_index=True)
#     def __unicode__(self):
#         return  self.task.id


class User_profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    select_limit = models.IntegerField(default=200)
    export_limit = models.IntegerField(default=200)
    task_email = models.IntegerField(db_index=True)
    def __unicode__(self):
        return  self.user.username
    class Meta:
        permissions = (('can_mysql_query','can see mysql_query view'),
                      ('can_log_query','can see log_query view'),
                      ('can_see_execview','can see mysql exec view'),
                      ('can_see_inception', 'can see inception view'),
                      ('can_see_metadata', 'can see meta_data view'),
                      ('can_see_mysqladmin', 'can see mysql_admin view'),
                      ('can_export','can export csv'),
                      ('can_insert_mysql','can insert mysql'),
                      ('can_update_mysql','can update mysql'),
                      ('can_delete_mysql','can delete mysql'),
                      ('can_create_mysql','can create mysql'),
                      ('can_drop_mysql','can drop mysql'),
                      ('can_truncate_mysql','can truncate mysql'),
                      ('can_alter_mysql','can alter mysql'),
                      ('can_query_mongo', 'can query mongo'),
                      ('can_see_taskview', 'can see task view'),
                      ('can_admin_task','can admin task'),
                      ('can_delete_task', 'can delete task'),
                      ('can_update_task', 'can update task'),
                      ('can_query_pri', 'can query pri'),
                      ('can_set_pri', 'can set pri'),
                      ('can_oper_saltapi', 'can oper saltapi'),
                       )

class Upload(models.Model):
    username = models.CharField(max_length = 40)
    filename = models.FileField(upload_to = 'upload_sql')
    def __unicode__(self):
        return self.username
# Create your models here.
class Task(models.Model):
    user = models.CharField(max_length=35)
    instance = models.CharField(max_length=100)
    db_account_role = models.CharField(max_length=15)
    dbtag = models.CharField(max_length=35)
    sqltext = models.TextField()
    create_time = models.DateTimeField(db_index=True)
    update_time = models.DateTimeField()
    status = models.CharField(max_length=20,db_index=True)
    sqlsha =  models.TextField()
    sche_time = models.DateTimeField(db_index=True,null=True)
    specification = models.CharField(max_length=100,default='')
    operator = models.CharField(max_length=35, default='')
    backup_status = models.SmallIntegerField(default=1)
    def __unicode__(self):
        return self.dbtag
#backup_status
# o donot  backup
# 1 need  backup
# 2

class Incep_error_log(models.Model):
    task_id = models.IntegerField(null=True,default=0)
    myid = models.IntegerField()
    stage = models.CharField(max_length= 20)
    errlevel = models.IntegerField()
    stagestatus = models.CharField(max_length=40)
    errormessage = models.TextField()
    sqltext = models.TextField()
    affectrow = models.IntegerField()
    sequence = models.CharField(max_length=30,db_index=True)
    backup_db = models.CharField(max_length=100)
    execute_time = models.CharField(max_length=20)
    sqlsha = models.CharField(max_length=50)
    create_time = models.DateTimeField(db_index=True)
    finish_time = models.DateTimeField()

class MySQL_monitor(models.Model):
    tag = models.CharField(max_length=20)
    monitor = models.SmallIntegerField(default=1)
    instance = models.OneToOneField(Db_instance)
    # instance = models.ForeignKey(Db_instance)
    check_longsql = models.SmallIntegerField(default=0)
    longsql_time = models.SmallIntegerField(default=1200)
    longsql_autokill = models.SmallIntegerField(default=0)
    check_active = models.SmallIntegerField(default=0)
    active_threshold = models.SmallIntegerField(default=30)
    # account = models.OneToOneField(Db_account)
    table_check = models.SmallIntegerField(default=0)
    account = models.ForeignKey(Db_account)
    check_connections = models.SmallIntegerField(default=0)
    connection_threshold = models.IntegerField(default=1000)
    check_delay = models.SmallIntegerField(default=0)
    delay_threshold = models.IntegerField(default=3600)
    check_slave = models.SmallIntegerField(default=0)
    replchannel = models.CharField(max_length=30,default='0')
    alarm_times = models.SmallIntegerField(default=3)
    alarm_interval = models.SmallIntegerField(default=60)
    mail_to = models.CharField(max_length=255)
    def __unicode__(self):
        return self.tag
    class Meta:
        db_table = 'mysql_monitor'

dbmanage/myapp/templates/diff.html
{% extends "include/base.html" %}
{% block title %}
    <title>表结构比对</title>
{% endblock %}
{% block name %}
    欢迎使用MySQL数据库<span style="color:red">表结构比对</span>功能
{% endblock %}
{%block db_content%}
    <div id="wrapper">
        <div id="page-content-wrapper">

            <form role="form" method='post'>
                {% csrf_token %}
{#                {% include "include/sidebar.html" %}#}
                <div class="row">
                    <div class="col-md-2">
                        选择比对库和表
                    </div>
                    <div class="col-md-2 col-md-offset-4">
                        选择参照库和表
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">

                        <select onchange="Change1()" id="dbid1" class="form-control col-md-1" title="选择比对库" name = "choosedb1">
                            <option value ="">----------</option>
                            {% for obj in objlist %}
                                {% if obj == choosed_host1 %}
                                    <option selected="selected" value ="{{ obj }}">{{ obj }}</option>
                                {% else %}
                                    <option value ="{{ obj }}">{{ obj }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3">
                        <select id="tbid1" class="form-control col-md-1" title="选择比对表"  name = "choosetb1">
                            {% if choosed_tb1 %}
                                <option selected="selected" value ="{{ choosed_tb1 }}">{{ choosed_tb1 }}</option>

                            {% else %}
                                <option selected="selected" value ="">----------</option>
                            {% endif %}
                        </select>

                    </div>
                    <div class="col-md-3">
                        <select onchange="Change2()" id="dbid2" class="form-control col-md-1" title="选择参照库" name = "choosedb2">
                            <option value ="">----------</option>
                            {% for obj in objlist %}
                                {% if obj == choosed_host2 %}
                                    <option selected="selected" value ="{{ obj }}">{{ obj }}</option>
                                {% else %}
                                    <option value ="{{ obj }}">{{ obj }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3">
                        <select id="tbid2" class="form-control col-md-1"  title="选择参照表" name = "choosetb2">
                            {% if choosed_tb2 %}
                                <option selected="selected" value ="{{ choosed_tb2 }}">{{ choosed_tb2 }}</option>

                            {% else %}
                                <option selected="selected" value ="">----------</option>
                            {% endif %}
                        </select>
                    </div>

                </div>
                <hr />
                <div class="row">
                    <div class="col-md-1">
                        <button type="submit" name='check' class="btn btn-warning" >比对表结构</button>

                    </div>
                    <div class="col-md-1">
                        <button onclick="openpage('{% url 'diff' %}')"  class="btn btn-info">刷新</button>
                    </div>
                </div>


            </form >

            {% if sh_cre1 %}


            {% endif %}
            {% if result %}
                <hr />
                <div class="row">
                    <div class="col-md-6" style="background-color: #dedef8; box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">

                        {{ sh_cre1.0.1|linebreaks }}
                    </div>
                    <div class="col-md-6" style="background-color: #dedef8; box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">
                        {{ sh_cre2.0.1|linebreaks }}
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-12" style="background-color: #dedef8; box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;">

                        {{ result|linebreaks }}
                    </div>
                </div>

            {% endif %}


        </div>
    </div>




{% block script %}
    {% include "include/pagejump/pagejump.html" %}
    {#    {% include "include/pagejump/tabledata.html" %}#}
    <script>
        function Change1() {
            var dbtag=$("#dbid1").val();
            $("#tbid1").empty("");
            $.get("{% url 'get_tblist' %}",{'dbtag':dbtag}).done(function (data) {
                for (var i =0 ; i <= data.length - 1; i++) {
                    $("#tbid1").append("<option value='" + data[i]  + "'>" + data[i] + "</option>");

                };
            });
        }
        function Change2() {
            var dbtag=$("#dbid2").val();
            $("#tbid2").empty("");
            $.get("{% url 'get_tblist' %}",{'dbtag':dbtag}).done(function (data) {
                for (var i =0 ; i <= data.length - 1; i++) {
                    $("#tbid2").append("<option value='" + data[i]  + "'>" + data[i] + "</option>");

                };
            });
        }


    </script>

{#        <script>#}
{##}
{#            $("#menu-toggle").click(function(e) {#}
{#                e.preventDefault();#}
{#                $("#wrapper").toggleClass("toggled");#}
{#            });#}
{#            function record_cookie() {#}
{#                var fav = document.getElementById("id_favword");#}
{#                myfav =escape(fav.value);#}
{#                myfav = fav.value.replace(/\n/g,"^");#}
{#                var expires = new Date();#}
{#                expires.setTime(expires.getTime() + 3500000);#}
{#                pathstr = ';path=/';#}
{#                alert(myfav);#}
{#                document.cookie = "myfavword"+"="+myfav+pathstr+';expires='+expires.toGMTString();#}
{#            }#}
{##}
{#            function showfav() {#}
{#                var fav = document.getElementById("id_favword");#}
{#                myfav =unescape(fav.value);#}
{#                fav.value = myfav;#}
{#            }#}
{#        </script>#}

{% endblock %}
{% endblock %}

dbmanage/myapp/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>MyTITLE</title>
    <!-- Bootstrap core CSS -->

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="theme.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
</head>
<body>

<table border="1">
    <tr>
        {% for colname in col %}
            <th>{{ colname }}</th>
        {% endfor %}
    </tr>
    {% for item in book_list %}
        <tr>
            {% for item_detail in item %}
                <td> {{ item_detail }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
</body>
</html>

dbmanage/myapp/templates/perm_detail_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
</head>
<body>

<div class="col-md-10 main" id="perm_edit" >
     <form class="form-horizontal" action="{% url 'perm_detail_edit' db_database_permission_id %}" method="POST">
                        {% csrf_token %}
     <div class="box" >

         <div class="box box-body col-md-12">
            <div class="form-group col-md-3">
                <h4><label>Permission:</label></h4>

                {% if permission_has.0 == -1 %}

                    {% for perm in perm_list %}
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" disabled value="{{ perm }}" name="check_box_list">
                          {{ perm|upper }}
                        </label>
                      </div>
                    {% endfor %}
                 {% else %}
                     {% for perm in perm_list %}
                      <div class="checkbox">
                        <label>
                            {% if perm in permission_has %}
                          <input type="checkbox" checked value="{{ perm }}" name="check_box_list">
                            {% else %}
                            <input type="checkbox"  value="{{ perm }}" name="check_box_list">
                            {% endif %}
                          {{ perm|upper }}
                        </label>
                      </div>
                    {% endfor %}
                 {% endif %}


        </div>
           <div class="form-group col-md-7">

                <h4><label>Black Table:</label></h4>
                <select id="id_black_table" name="black_table" multiple="multiple" style="width:100%;height: 100px;">
                {% if black_table_has %}
                    {% for b in black_table_has %}
                        <option value="{{ b }}">{{ b }}</option>
                    {% endfor %}
                {% endif %}
                </select>
                <div class="input-group">
                    <input id="id_black_table_name" type="text" class="form-control" placeholder="DB Name">

                    <div class="input-group-btn">
                        <button  style="width: 50px" id="id_black_table_add" type="button" class="btn btn-primary btn-flat">Add</button>
                     <button  style="width: 50px" id="id_black_table_delete" type="button" class="btn btn-primary btn-danger">Del</button>

                    </div>
                    <!-- /btn-group -->
                  </div>

            </div>
         </div>
          <div class="box-footer">
                <button type="submit" onclick="fetch_table_name()" class="btn btn-info pull-left center-block" style="width: 120px"><b>保存</b></button>
          </div>   <!-- /.modal-content -->
     </div>
         <input type="text" id="table_name" name="table_name" hidden>
          <!-- /.modal-dialog -->
  </form>


</div>
<script>
    function fetch_table_name(){

        var array = []
         $("#id_black_table option").each(function(){  //遍历所有option
          var txt = $(this).val();   //获取option值
          if(txt!=''){
               array.push(txt);  //添加到数组中

          }
          console.log(array)
        $("#table_name").val(JSON.stringify(array))

    })
    }
</script>

    <script type="text/javascript">
        var index = parent.layer.getFrameIndex(window.name);
        var success = "{{ status }}";
        if ( success === '1' ) {
            parent.$("#handle_status").val('1');
              parent.layer.close(index);
        } else if( success === '2' ) {
            parent.$("#handle_status").val('2');
            parent.layer.close(index);
        }
</script>

<script>


function isInList( num, list ) {
// List is an Array()
result = false;
for(i in list) {
if(num == list[i]) { result = true }
}
return result
}
   $('#id_black_table_add').click(function () {

      //Get value and make sure it is not null
      var val = $('#id_black_table_name').val();

      if (val.length == 0) {
        return
      }
      else {

           var l = []
        $("#id_black_table").find('option').each(function(){  //遍历所有option
          var txt = $(this).val();   //获取option值
            l.push(txt)})
          if(! isInList(val,l)){
               $("#id_black_table").append('<option value="'+val+'">'+val+'</option>')
                $('#id_black_table_name').val('') }

              else{return}
      }
 })

$('#id_black_table_delete').click(function(){
{#    console.log($('#id_select_all').find('option:selected').val());#}
    $('#id_black_table').find('option:selected').remove()
})
</script>

</body>
</html>