adminset/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^dbmanage/',include('dbmanage.urls')),
    url(r'^test/$',views.test,name='test'),
    url(r'^add/$',views.add,name='add'),
    url(r'^ajax_dict',views.ajax_dict,name='ajax_dict'),
    url(r'^ajax_list',views.ajax_list,name='ajax_list'),
    url(r'^forbidden/',views.forbidden,name='forbidden'),

]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group


urlpatterns = [
    url(r'asset/$', asset.asset, name='cmdb'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_del, name='asset_del'),
    url(r'^asset/edit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^group/del/$', group.group_del, name='group_del'),
    url(r'^group/add/$', group.group_add, name='group_add'),
    url(r'^group/edit/(?P<ids>\d+)/$', group.group_edit, name='group_edit'),
    url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_del, name='idc_del'),
    url(r'^idc/save/$', idc.idc_save, name='idc_save'),
    url(r'^idc/edit/(?P<ids>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^get/host/', api.get_host, name='get_host'),
    url(r'^get/group/', api.get_group, name='get_group'),
]

dbmanage/archer/archer/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('dbmanage.archer.sql.urls')),
]

if __name__ == '__main__':
    print(urlpatterns)

dbmanage/mypro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.views.static import serve
from myapp import views as myapp_view
urlpatterns = [
    url(r'^$', myapp_view.index, name='index'),
    url(r'^accounts/login/$',myapp_view.login,name='login'),
    url(r'^accounts/logout/$',myapp_view.logout,name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^log_query/$', myapp_view.log_query,name='log_query'),
    url(r'^mysql_query/$', myapp_view.mysql_query,name='mysql_query'),
    url(r'^mysql_admin/$', myapp_view.mysql_admin, name='mysql_admin'),
    url(r'^binlog_parse/$', myapp_view.mysql_binlog_parse,name='binlog_parse'),
    url(r'^tb_check/$', myapp_view.tb_check, name='tb_check'),
    url(r'^dupkey_check/$', myapp_view.dupkey_check, name='dupkey_check'),
    url(r'^meta_data/$', myapp_view.meta_data,name='meta_data'),
    url(r'^mysql_exec/$', myapp_view.mysql_exec,name='mysql_exec'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^sqlcheck/$', myapp_view.inception,name='inception'),

    url(r'^task/$', myapp_view.task_manager,name='task_manager'),
    url(r'^pre_query/$', myapp_view.pre_query,name='pre_query'),
    url(r'^pass_reset/$', myapp_view.pass_reset,name='pass_reset'),
    url(r'^pre_set/$', myapp_view.pre_set,name='pre_set'),
    url(r'^set_dbgroup/$', myapp_view.set_dbgroup,name='set_dbgroup'),
    url(r'^set_ugroup/$', myapp_view.set_ugroup,name='set_ugroup'),
    url(r'^fast_dbset/$', myapp_view.fast_dbset,name='fast_dbset'),
    url(r'^set_dbname/$', myapp_view.set_dbname,name='set_dbname'),
    url(r'^update_task/$', myapp_view.update_task,name='update_task'),
    url(r'^get_rollback/$', myapp_view.get_rollback,name='get_rollback'),
    url(r'^get_single_rollback/$', myapp_view.get_single_rollback,name='get_single_rollback'),
    url(r'^get_tblist/$', myapp_view.get_tblist, name='get_tblist'),
    url(r'^diff/$', myapp_view.diff,name='diff'),
    url(r'^salt/', include('salt.urls')),
    url(r'^mongodb/', include('dbmanage.mongodb.urls')),
    url(r'^chartapi/', include('dbmanage.chartapi.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^passforget/', include('dbmanage.passforget.urls')),
    url(r'^blacklist/', include('dbmanage.blacklist.urls')),
    url(r'^site_media/(?P<path>.*)$',serve,{'document_root': settings.MEDIA_ROOT}),

]

dbmanage/myapp/models.py
from __future__ import unicode_literals
# from django.contrib.auth.models import User
from django.db import models
import pytz
from django.conf import settings
from datetime import datetime
from django.utils import timezone
tz = pytz.timezone('UTC')
s_time = tz.localize(datetime.strptime('2199-01-01 00:00:00','%Y-%m-%d %H:%M:%S'))
read_write = (
    ('read', 'read'),
    ('write', 'write'),
    ('all','all'),
    ('idle','idle'),
)
read_write_account = (
    ('read', 'read'),
    ('write', 'write'),
    ('read_write','read_write'),
    ('admin','admin'),
    ('all','all'),
)
db_type = (
    ('mysql', 'mysql'),
    ('mongodb', 'write'),
)


class Db_instance(models.Model):
    ip = models.CharField(max_length=30)
    port = models.CharField(max_length=10)
    db_type = models.CharField(max_length=30,default='mysql')
    comments = models.CharField(max_length=100,null=True)
    status = models.CharField(max_length=20,choices=(('Idle','Idle'),('InUse','InUse')))

    admin_user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    create_user = models.CharField(max_length=50,null=True)
    create_date =models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s %s' % (self.ip, self.port,self.db_type)
    class Meta:
        unique_together = ("ip","port")



class Db_account(models.Model):

    user = models.CharField(max_length=30)
    passwd = models.CharField(max_length=255)
    instance = models.ForeignKey(Db_instance)
    db_account_role =  models.CharField(max_length=30,choices=read_write_account,default='all')
    tags = models.CharField(max_length=80,db_index=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    # dbname = models.ManyToManyField(Db_name)
    # account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return  u'%s %s' % ( self.tags,self.db_account_role)

    class Meta:
        unique_together = ('instance','db_account_role')

class Db_name (models.Model):
    dbtag = models.CharField(max_length=80)
    dbname = models.CharField(max_length=30)
    dbaccount = models.ForeignKey(Db_account)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())
    def __unicode__(self):
        return u'%s %s' % (self.dbtag, self.dbname)

class Instance_account_admin(models.Model):
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    db_account = models.ForeignKey(Db_account)
class Db_database_permission(models.Model):
    db_name = models.ForeignKey(Db_name)
    account = models.ForeignKey(settings.AUTH_USER_MODEL)
    permission = models.CharField(max_length=20,choices=read_write_account,default='read')
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_database_permission_detail(models.Model):
    permission = models.ForeignKey(Db_database_permission)
    permission_detail = models.CharField(max_length=500,null=True)
    black_table = models.CharField(max_length=500,null=True)
    create_user = models.CharField(max_length=50, null=True)
    create_date = models.DateTimeField(auto_now_add=timezone.now())
    update_user = models.CharField(max_length=50, null=True)
    update_date = models.DateTimeField(auto_now=timezone.now())

class Db_group(models.Model):
    groupname = models.CharField(max_length=30,unique=True)
    dbname = models.ManyToManyField(Db_name)
    account = models.ManyToManyField(settings.AUTH_USER_MODEL)
    def __unicode__(self):
        return self.groupname

class Oper_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    dbtag = models.CharField(max_length=35)
    dbname = models.CharField(max_length=300)
    sqltext = models.TextField()
    sqltype = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)
    login_time = models.DateTimeField()
    group_id = models.IntegerField()
    host_id = models.IntegerField()
    def __unicode__(self):
        return self.dbtag
    class Meta:
        index_together = [["dbtag","sqltype", "create_time"],]

class Login_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    action = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)

# class Task_scheduler(models.Model):
#     task = models.OneToOneField(Task)
#     appoint_time = models.DateTimeField(db_index=True)
#     def __unicode__(self):
#         return  self.task.id


class User_profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    select_limit = models.IntegerField(default=200)
    export_limit = models.IntegerField(default=200)
    task_email = models.IntegerField(db_index=True)
    def __unicode__(self):
        return  self.user.username
    class Meta:
        permissions = (('can_mysql_query','can see mysql_query view'),
                      ('can_log_query','can see log_query view'),
                      ('can_see_execview','can see mysql exec view'),
                      ('can_see_inception', 'can see inception view'),
                      ('can_see_metadata', 'can see meta_data view'),
                      ('can_see_mysqladmin', 'can see mysql_admin view'),
                      ('can_export','can export csv'),
                      ('can_insert_mysql','can insert mysql'),
                      ('can_update_mysql','can update mysql'),
                      ('can_delete_mysql','can delete mysql'),
                      ('can_create_mysql','can create mysql'),
                      ('can_drop_mysql','can drop mysql'),
                      ('can_truncate_mysql','can truncate mysql'),
                      ('can_alter_mysql','can alter mysql'),
                      ('can_query_mongo', 'can query mongo'),
                      ('can_see_taskview', 'can see task view'),
                      ('can_admin_task','can admin task'),
                      ('can_delete_task', 'can delete task'),
                      ('can_update_task', 'can update task'),
                      ('can_query_pri', 'can query pri'),
                      ('can_set_pri', 'can set pri'),
                      ('can_oper_saltapi', 'can oper saltapi'),
                       )

class Upload(models.Model):
    username = models.CharField(max_length = 40)
    filename = models.FileField(upload_to = 'upload_sql')
    def __unicode__(self):
        return self.username
# Create your models here.
class Task(models.Model):
    user = models.CharField(max_length=35)
    instance = models.CharField(max_length=100)
    db_account_role = models.CharField(max_length=15)
    dbtag = models.CharField(max_length=35)
    sqltext = models.TextField()
    create_time = models.DateTimeField(db_index=True)
    update_time = models.DateTimeField()
    status = models.CharField(max_length=20,db_index=True)
    sqlsha =  models.TextField()
    sche_time = models.DateTimeField(db_index=True,null=True)
    specification = models.CharField(max_length=100,default='')
    operator = models.CharField(max_length=35, default='')
    backup_status = models.SmallIntegerField(default=1)
    def __unicode__(self):
        return self.dbtag
#backup_status
# o donot  backup
# 1 need  backup
# 2

class Incep_error_log(models.Model):
    task_id = models.IntegerField(null=True,default=0)
    myid = models.IntegerField()
    stage = models.CharField(max_length= 20)
    errlevel = models.IntegerField()
    stagestatus = models.CharField(max_length=40)
    errormessage = models.TextField()
    sqltext = models.TextField()
    affectrow = models.IntegerField()
    sequence = models.CharField(max_length=30,db_index=True)
    backup_db = models.CharField(max_length=100)
    execute_time = models.CharField(max_length=20)
    sqlsha = models.CharField(max_length=50)
    create_time = models.DateTimeField(db_index=True)
    finish_time = models.DateTimeField()

class MySQL_monitor(models.Model):
    tag = models.CharField(max_length=20)
    monitor = models.SmallIntegerField(default=1)
    instance = models.OneToOneField(Db_instance)
    # instance = models.ForeignKey(Db_instance)
    check_longsql = models.SmallIntegerField(default=0)
    longsql_time = models.SmallIntegerField(default=1200)
    longsql_autokill = models.SmallIntegerField(default=0)
    check_active = models.SmallIntegerField(default=0)
    active_threshold = models.SmallIntegerField(default=30)
    # account = models.OneToOneField(Db_account)
    table_check = models.SmallIntegerField(default=0)
    account = models.ForeignKey(Db_account)
    check_connections = models.SmallIntegerField(default=0)
    connection_threshold = models.IntegerField(default=1000)
    check_delay = models.SmallIntegerField(default=0)
    delay_threshold = models.IntegerField(default=3600)
    check_slave = models.SmallIntegerField(default=0)
    replchannel = models.CharField(max_length=30,default='0')
    alarm_times = models.SmallIntegerField(default=3)
    alarm_interval = models.SmallIntegerField(default=60)
    mail_to = models.CharField(max_length=255)
    def __unicode__(self):
        return self.tag
    class Meta:
        db_table = 'mysql_monitor'

dbmanage/myapp/templates/include/pagejump/bak/mysql_query_bak.html
{% extends "include/base.html" %}
{% block title %}
    <title>MySQL_QUERY</title>
{% endblock %}
{% block name %}
    欢迎使用MySQL数据库查询功能
{% endblock %}
{%block content%}
    <table >
        <tr>
            <td>
            </br>
            </br>
                <form role="form" method='post'>
                    {% csrf_token %}
                    CHOOSE :
                    {%  if choosed_host %}
                        <select class="form-control col-md-1" name = "cx">
                            <option value ="{{ choosed_host }}">{{ choosed_host }}</option>
                        </select></br>
                        <a href="/mysql_query/"><input type="button" value="重选数据源" class="btn btn-danger"></a>
                    {% else %}
                        <select class="form-control col-md-1" name = "cx">
                            {% for obj in objlist %}
                                <option value ="{{ obj }}">{{ obj }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                    </br> </br>
                    请在下面输入查询语句:</br>
                    {{ form.a }} </br> </br>
                    <button type="submit" name='query' class="btn btn-primary" value="1">提交</button >
                    <button type="submit" name='explain' class="btn btn-info" value="1">查看执行计划</button>
                {% if perms.myapp.can_export %}
                    <button type="submit" name='export' class="btn btn-warning" value="1">导出CSV</button>
                {% endif %}
                </form >
            </td>
            <td>
                <div class="col-md-12">
                    <h3>查询注意事项:</h3>
                    <p class="bg-danger"> 1. 支持单条语句查询，勿在框中重复输入多条sql语句</p>
                    <p> 2. 平台默认查询和导出限制都是200行
                    <p> 3. 增加查询或导出数据行数限制，需提需求给DBA开通权限</p>
                    <p> 4. 查看表结构语句如:show create table (dbname.)tablename</p>
                    <p> 5. 查看表结构语句如:desc (dbname.)tablename或者show fields in (dbname.)tablename</p>
                    <p> 6. 查看执行计划可以直接点击按钮或者输入"explain (extended) select..."然后点击提交</p>
                    <p> 7. 查看库中的表名如: show tables (in dbname)</p>
                    <p> 8. 查看所有的库名如: show databases</p>
                    <p class="bg-danger"> 9. 导出CSV文件为GBK编码格式</p>

                </div>
            </td>
        </tr>
    </table>

    {% if collist %}
        <table  class="table table-condensed" border="1">
            <tr class="danger">
                QUERY IN:{{ dbname }}
            </tr>
        </table>
        {% include "include/pagejump/pagebutton.html" %}
    {% endif %}
    <table id="mytable" class="table table-condensed" border="1">
        <thead>
        <tr class="danger">
            {% for colname in collist %}
                <th>{{ colname }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody  >
        {% for item in data_list %}
            <tr>
                {% for item_detail in item %}
                    <td> {{ item_detail }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}
{% block script %}
    {% include "include/pagejump/pagejump.html" %}
{% endblock %}

dbmanage/myapp/templates/include/pagejump/bak/task_manager.html
{% extends "include/base.html" %}
{% block title %}
    <title>TASK_MANAGER</title>
{% endblock %}
{% block name %}
    欢迎使用任务管理功能
{% endblock %}
{%block content%}
    <form role="form" method='post'>
        <table >
            <tr>
                <td>
                    </br>
                    </br>

                    {% csrf_token %}
                    CHOOSE:</br>
                    {%  if choosed_host %}
                        <select class="form-control col-md-1" name = "hosttag">
                            <option value ="{{ choosed_host }}">{{ choosed_host }}</option>
                        </select></br>
                        截止时间：{{ form.end }} </br>
                        <a href="/task/"><input type="button" value="重选数据源" class="btn btn-danger"></a>
                    {% else %}
                        <select class="form-control col-md-1" name = "hosttag">
                            {% for obj in objlist %}
                                <option value ="{{ obj }}">{{ obj }}</option>
                            {% endfor %}
                        </select>
                        选择截止时间:</br>{{ form.end }} </br>
                    {% endif %}

                    <button type="submit" name='commit' class="btn btn-primary">查询任务</button >


                </td>
                <td>
                    <div class="col-md-10">
                        <h3>注意事项:</h3>
                        <p> 1. 输出结果默认按时间倒序</p>
                        <p> 2. 已执行成功的task状态不能修改</p>
                        <p> 3. 默认返回最新50项任务</p>
                    </div>
                </td>
                <td>

                </td>
            </tr>
        </table>
        <script type="text/javascript">
            jeDate({
                dateCell:"#id_end",
                format:"YYYY-MM-DD hh:mm:ss",
                isinitVal:true,
                isTime:true, //isClear:false,
                minDate:"2014-09-19 00:00:00",
                okfun:function(val){alert(val)}
            })
        </script>
        {% if nllflag %}
            </br>
            <strong> {{ nllflag }}</strong>
        {% endif %}
        {% if result %}
            {% include "include/pagejump/pagejump2.html" %}
            <table id="mytable1" class="table table-condensed" border="1">
                <thead>
                <tr class="danger">
                    {% for colname in col %}
                        <th>{{ colname }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody  >
                {% for item in result %}
                    <tr>
                        {% for item_detail in item %}
                            {% if forloop.counter == 6 %}
                                <td> {{ item_detail|truncatechars:550|linebreaks}}</td>
                            {% elif forloop.counter == 5 %}
                                <td> {{ item_detail|linebreaks}}</td>
                            {% else %}
                                <td> {{ item_detail }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}


        {% if result_status %}
            {% include "include/pagejump/pagejump2.html" %}
            <table id="mytable1" class="table table-condensed" border="1">
                <thead>
                <tr class="danger">
                    {% for colname in cols %}
                        <th>{{ colname }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody  >
                {% for item in result_status %}
                    <tr>
                        {% if item.myid %}
                            <td> {{ item.myid }}</td>
                            <td> {{ item.stage }}</td>
                            <td> {{ item.errlevel }}</td>
                            <td> {{ item.stagestatus|linebreaks }}</td>
                            <td> {{ item.errormessage|linebreaks }}</td>
                            <td> {{ item.sqltext|linebreaks }}</td>
                            <td> {{ item.affectrow }}</td>
                            <td> {{ item.sequence|truncatechars:10  }}</td>
                            <td> {{ item.backup_db}}</td>
                            <td> {{ item.execute_time }}</td>
                            <td> {{ item.sqlsha|truncatechars:7 }}</td>
                            <td> {{ item.create_time|date:"Y-m-d H:i:s"  }}</td>
                            <td> {{ item.finish_time|date:"Y-m-d H:i:s"  }}</td>
                        {% else %}
                            {% for item_detail in item %}
                                {% if forloop.counter == 6 %}
                                    <td> {{ item_detail|linebreaks}}</td>
                                {% elif forloop.counter == 7 %}
                                    <td> {{ item_detail|truncatechars:150|linebreaks}}</td>
                                {% else %}
                                    <td> {{ item_detail }}</td>
                                {% endif %}
                            {% endfor %}
                            {% if perms.myapp.can_admin_task %}
                                {% if 'SQLSHA1' in cols %}
                                    {% if '*' in item.2 %}
                                        <td><button type="submit" name='stop' class="btn btn-danger" value={{ item.2 }}>停止</button></td>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </tr>
                    <tr>
                        {% if 'SQLSHA1' in cols %}
                            {% if '*' in item.2 %}
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow=item.3 aria-valuemin="0" aria-valuemax="100" style="width: {{ item.3 }}%;" >
                                        {{ item.3 }}%
                                    </div>
                                </div>
                            {% endif %}
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}




        </br>
        </br>
        {% if datalist %}
            {% include "include/pagejump/pagebutton.html" %}
        {% endif %}
        <body onload="checkstatus()">
        <table id="mytable" class="table table-condensed" border="1">
            <thead>
            <tr class="danger">
                <th>ID</th>
                <th>USER</th>
                <th>DBTAG</th>
                <th>SQL语句</th>
                <th>创建时间</th>
                <th>修改时间</th>
                <th>任务状态</th>
                <th>预约时间</th>
                <th>操作</th>
                <th></th>
                <th></th>
                {% if perms.myapp.can_admin_task %}
                    <th>选择时间</br> {{ form2.sche_time }}</th>
                {% endif %}
                <th></th>
            </tr>
            </thead>
            <tbody  >
            {% for item in datalist %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td> {{ item.user }}</td>
                    <td> {{ item.dbtag }}</td>
                    <td> {{ item.sqltext|truncatechars:100|linebreaks }}</td>
                    <td> {{ item.create_time|date:"Y-m-d H:i:s" }}</td>
                    <td> {{ item.update_time|date:"Y-m-d H:i:s" }}</td>
                    <td > {{ item.status }}</td>
                    <td > {{ item.sche_time|date:"Y-m-d H:i" }}</td>
                    <td><button type="submit" name='delete' class="btn btn-primary" value={{ item.id }}>删除</button></td>
                    <td><button type="submit" name='check' class="btn btn-warning" value={{ item.id }}>审核</button></td>
                    {% if perms.myapp.can_admin_task %}
                        <td><button type="submit" name='exec' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-danger" value={{ item.id }}>执行</button></td>
                        <td><button type="submit" name='appoint' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-success" value={{ item.id }}>预约时间执行</button></td>
                    {% endif %}
                    <td><button type="submit" name='see_running' class="btn btn-info" value={{ item.id }}>查询状态</button></td>
                </tr>
            {% endfor %}
            <script>
                jeDate({
                    dateCell:"#id_sche_time",
                    format:"YYYY-MM-DD hh:mm:ss",
                    isinitVal:true,
                    isTime:true, //isClear:false,
                    minDate:"2014-09-19 00:00:00",
                    okfun:function(val){alert(val)}
                })
                function checkstatus() {
                    var tableId = document.getElementById("mytable");
                    var str = "";
                    for (var i = 1; i < tableId.rows.length; i++) {
                        var value = tableId.rows[i].cells[6];
                        if (value.innerText == "executed") {
                            value.setAttribute("class", "success");

                        }
                        else if (value.innerText == "check passed") {
                            value.setAttribute("class", "warning");

                        }
                        else if (value.innerText == "running") {
                            value.setAttribute("class", "active");
                        }
                        else {
                            value.setAttribute("class", "danger");
                        }
                        var sched = tableId.rows[i].cells[7];
                        if (sched.innerText == "2199-01-01 00:00"){
                            sched.innerText='NOT SCHEDULED';
                            sched.setAttribute("class", "danger");

                        }
                        else{
                            sched.setAttribute("class", "active");

                        }
                    }
                }

            </script>

            </tbody>
        </table>
        </body>
    </form>
    <script type="text/javascript">


        {#        var mystatus = document.getElementById("taskstatus");#}
        {#        for (i=0;i<=mystatus.length-1;i++)#}
        {#        {#}
        {##}
        {#            if (mystatus[i].innerHTML == 'check not passed') {#}
        {#                mystatus[i].class = "bg-danger";#}
        {#            }#}
        {#        }#}
        //jeDate.skin('gray');
        {#        jeDate({#}
        {#            dateCell:"#id_begin",#}
        {#            format:"YYYY-MM-DD hh:mm:ss",#}
        {#            isinitVal:true,#}
        {#            isTime:true, //isClear:false,#}
        {#            minDate:"2014-09-19 00:00:00",#}
        {#            okfun:function(val){alert(val)}#}
        {#        })#}
        {#        jeDate({#}
        {#            dateCell:"#id_end",#}
        {#            format:"YYYY-MM-DD hh:mm:ss",#}
        {#            isinitVal:true,#}
        {#            isTime:true, //isClear:false,#}
        {#            minDate:"2014-09-19 00:00:00",#}
        {#            okfun:function(val){alert(val)}#}
        {#        })#}
    </script>
{% endblock %}
{% block script %}
    {% include "include/pagejump/pagejump.html" %}

{% endblock %}

dbmanage/myapp/templates/include/pagejump/bak/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>